packages:
  - "extensions/*"
useNodeVersion: "24.14.0"
overrides:
  electron-builder-squirrel-windows: "26.8.1"
onlyBuiltDependencies:
  - electron
  - esbuild
  - "@vscode/vsce-sign"
  - keytar
  - sleep
  - electron-winstaller
