/**
 * API event wiring and window title utilities.
 *
 * These utilities bridge API events to IPC emission and format window titles.
 * IPC handlers are now auto-generated by the ApiRegistry when modules register methods.
 */

import type { WebContents } from "electron";
import type { ICodeHydraApi, Unsubscribe } from "../../shared/api/interfaces";
import { ApiIpcChannels } from "../../shared/ipc";

// =============================================================================
// Window Title Formatting
// =============================================================================

/**
 * Configuration for dynamic window title updates.
 */
export interface TitleConfig {
  /** Function to set the window title */
  setTitle: (title: string) => void;
  /** Default title (used when no workspace active) */
  defaultTitle: string;
  /** Version suffix for title (branch in dev mode, version in packaged mode) */
  version?: string;
  /** Function to resolve project name from workspace path */
  getProjectName: (workspacePath: string) => string | undefined;
}

/**
 * Formats the window title based on current workspace.
 *
 * Format: "CodeHydra - <project> / <workspace> - (<version>)"
 * No workspace: "CodeHydra - (<version>)" or "CodeHydra"
 *
 * @param projectName - Name of the active project, or undefined
 * @param workspaceName - Name of the active workspace, or undefined
 * @param version - Version suffix (branch in dev mode, version in packaged mode), or undefined
 * @returns Formatted window title
 */
export function formatWindowTitle(
  projectName: string | undefined,
  workspaceName: string | undefined,
  version?: string
): string {
  const base = "CodeHydra";
  const versionSuffix = version ? ` - (${version})` : "";

  if (projectName && workspaceName) {
    return `${base} - ${projectName} / ${workspaceName}${versionSuffix}`;
  }

  return `${base}${versionSuffix}`;
}

// =============================================================================
// Event Wiring
// =============================================================================

/**
 * Wire API events to IPC emission.
 *
 * Subscribes to all API events and forwards them to the renderer via webContents.send().
 * Optionally updates window title on workspace switches.
 *
 * @param api - The ICodeHydraApi instance to subscribe to
 * @param getWebContents - Function to get the WebContents to send events to
 * @param titleConfig - Optional configuration for window title updates
 * @returns Cleanup function that unsubscribes from all events
 */
export function wireApiEvents(
  api: ICodeHydraApi,
  getWebContents: () => WebContents | null,
  titleConfig?: TitleConfig
): Unsubscribe {
  const unsubscribers: Unsubscribe[] = [];

  // Helper to send events to renderer
  const send = (channel: string, payload?: unknown): void => {
    const webContents = getWebContents();
    if (webContents && !webContents.isDestroyed()) {
      webContents.send(channel, payload);
    }
  };

  // Project events
  unsubscribers.push(
    api.on("project:opened", (event) => {
      send(ApiIpcChannels.PROJECT_OPENED, event);
    })
  );

  unsubscribers.push(
    api.on("project:closed", (event) => {
      send(ApiIpcChannels.PROJECT_CLOSED, event);
    })
  );

  unsubscribers.push(
    api.on("project:bases-updated", (event) => {
      send(ApiIpcChannels.PROJECT_BASES_UPDATED, event);
    })
  );

  // Workspace events
  unsubscribers.push(
    api.on("workspace:created", (event) => {
      send(ApiIpcChannels.WORKSPACE_CREATED, event);
    })
  );

  unsubscribers.push(
    api.on("workspace:removed", (event) => {
      send(ApiIpcChannels.WORKSPACE_REMOVED, event);
    })
  );

  unsubscribers.push(
    api.on("workspace:switched", (event) => {
      send(ApiIpcChannels.WORKSPACE_SWITCHED, event);

      // Update window title if configured
      if (titleConfig) {
        if (event) {
          const projectName = titleConfig.getProjectName(event.path);
          const title = formatWindowTitle(projectName, event.workspaceName, titleConfig.version);
          titleConfig.setTitle(title);
        } else {
          titleConfig.setTitle(titleConfig.defaultTitle);
        }
      }
    })
  );

  unsubscribers.push(
    api.on("workspace:status-changed", (event) => {
      send(ApiIpcChannels.WORKSPACE_STATUS_CHANGED, event);
    })
  );

  unsubscribers.push(
    api.on("workspace:metadata-changed", (event) => {
      send(ApiIpcChannels.WORKSPACE_METADATA_CHANGED, event);
    })
  );

  // UI mode events
  unsubscribers.push(
    api.on("ui:mode-changed", (event) => {
      send(ApiIpcChannels.UI_MODE_CHANGED, event);
    })
  );

  // Lifecycle events
  unsubscribers.push(
    api.on("lifecycle:setup-progress", (event) => {
      send(ApiIpcChannels.LIFECYCLE_SETUP_PROGRESS, event);
    })
  );

  // Return cleanup function
  return () => {
    for (const unsubscribe of unsubscribers) {
      unsubscribe();
    }
  };
}
