/**
 * API event wiring and window title utilities.
 *
 * These utilities bridge API events to IPC emission and format window titles.
 * IPC handlers are now auto-generated by the ApiRegistry when modules register methods.
 *
 * Note: workspace:switched title updates are handled by WindowTitleModule in modules/window-title-module.ts.
 * IPC forwarding still goes through wireApiEvents like all other events.
 */

import type { WebContents } from "electron";
import type { ICodeHydraApi, Unsubscribe } from "../../shared/api/interfaces";
import { ApiIpcChannels } from "../../shared/ipc";

// =============================================================================
// Window Title Formatting
// =============================================================================

/**
 * Formats the window title based on current workspace.
 *
 * Format: "CodeHydra - <project> / <workspace> - (<version>) - (update available)"
 * No workspace: "CodeHydra - (<version>)" or "CodeHydra"
 *
 * @param projectName - Name of the active project, or undefined
 * @param workspaceName - Name of the active workspace, or undefined
 * @param version - Version suffix (branch in dev mode, version in packaged mode), or undefined
 * @param hasUpdate - Whether an update is available
 * @returns Formatted window title
 */
export function formatWindowTitle(
  projectName: string | undefined,
  workspaceName: string | undefined,
  version?: string,
  hasUpdate?: boolean
): string {
  const base = "CodeHydra";
  const versionSuffix = version ? ` - (${version})` : "";
  const updateSuffix = hasUpdate ? ` - (update available)` : "";

  if (projectName && workspaceName) {
    return `${base} - ${projectName} / ${workspaceName}${versionSuffix}${updateSuffix}`;
  }

  return `${base}${versionSuffix}${updateSuffix}`;
}

// =============================================================================
// Event Wiring
// =============================================================================

/**
 * Wire API events to IPC emission.
 *
 * Subscribes to API events and forwards them to the renderer via webContents.send().
 * Note: workspace:switched title updates are handled by WindowTitleModule in modules/window-title-module.ts.
 *
 * @param api - The ICodeHydraApi instance to subscribe to
 * @param getWebContents - Function to get the WebContents to send events to
 * @returns Cleanup function that unsubscribes from all events
 */
export function wireApiEvents(
  api: ICodeHydraApi,
  getWebContents: () => WebContents | null
): Unsubscribe {
  const unsubscribers: Unsubscribe[] = [];

  // Helper to send events to renderer
  const send = (channel: string, payload?: unknown): void => {
    const webContents = getWebContents();
    if (webContents && !webContents.isDestroyed()) {
      webContents.send(channel, payload);
    }
  };

  // Project events
  unsubscribers.push(
    api.on("project:opened", (event) => {
      send(ApiIpcChannels.PROJECT_OPENED, event);
    })
  );

  unsubscribers.push(
    api.on("project:closed", (event) => {
      send(ApiIpcChannels.PROJECT_CLOSED, event);
    })
  );

  unsubscribers.push(
    api.on("project:bases-updated", (event) => {
      send(ApiIpcChannels.PROJECT_BASES_UPDATED, event);
    })
  );

  // Workspace events
  unsubscribers.push(
    api.on("workspace:created", (event) => {
      send(ApiIpcChannels.WORKSPACE_CREATED, event);
    })
  );

  unsubscribers.push(
    api.on("workspace:removed", (event) => {
      send(ApiIpcChannels.WORKSPACE_REMOVED, event);
    })
  );

  unsubscribers.push(
    api.on("workspace:switched", (event) => {
      send(ApiIpcChannels.WORKSPACE_SWITCHED, event);
    })
  );

  unsubscribers.push(
    api.on("workspace:status-changed", (event) => {
      send(ApiIpcChannels.WORKSPACE_STATUS_CHANGED, event);
    })
  );

  unsubscribers.push(
    api.on("workspace:metadata-changed", (event) => {
      send(ApiIpcChannels.WORKSPACE_METADATA_CHANGED, event);
    })
  );

  // UI mode events
  unsubscribers.push(
    api.on("ui:mode-changed", (event) => {
      send(ApiIpcChannels.UI_MODE_CHANGED, event);
    })
  );

  // Lifecycle events
  unsubscribers.push(
    api.on("lifecycle:setup-progress", (event) => {
      send(ApiIpcChannels.LIFECYCLE_SETUP_PROGRESS, event);
    })
  );

  // Return cleanup function
  return () => {
    for (const unsubscribe of unsubscribers) {
      unsubscribe();
    }
  };
}
